#!/usr/bin/env zsh

# Source any extra zsh configs
for CONFIG in $(find ~ -maxdepth 1 -name ".zshrc-*"); do
    source $CONFIG
done

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# PATH
#=========================================================
export PATH=/usr/local/sbin:$PATH         # Homebrew sbin
export PATH=/opt/homebrew/bin:$PATH       # New homebrew bin
export PATH=$HOME/.dotfiles/bin:$PATH     # Personal bin
export PATH=$HOME/venvs/bin:$PATH         # bins for isolated venv installs of packages
export PATH=$HOME/.local/bin:$PATH        # pipx bin location
export PATH=$HOME/.poetry/bin:$PATH       # Poetry path
export PATH=$HOME/.emacs.d/bin:$PATH      # DOOM emacs
export PATH=$HOME/.cargo/bin:$PATH
export PATH=/usr/local/go/bin:$PATH

# PYENV Configuration
#=====================================================
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - --no-rehash)"

# Set ZSH 
#=========================================================
# zsh env variables
ZSH_THEME="grado"

# zsh themes
plugins=(git)
unsetopt AUTO_CD  # Don't cd w/o `cd`

# source zsh
source $ZSH/oh-my-zsh.sh

# Make ls colors work properly
unset LSCOLORS

# Emacs and Editor vars
#======================================================
export EDITOR="emacs"
source $HOME/.dotfiles/zsh/emacsd.sh

# ALIASES
#======================================================
alias ls='ls -CFG'
alias lsa='ls -CFGa'
alias del='rmtrash'
alias g++='g++ -std=c++11'

# DOCKER ALIASES
# Rootless/rootful
alias docker-rootless='export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock && echo "Switched to rootless Docker"'
alias docker-rootful='export DOCKER_HOST=unix:///var/run/docker.sock && echo "Switched to rootfull Docker"'
alias dive="docker run -ti --rm  -v ${DOCKER_HOST#unix://}:/var/run/docker.sock wagoodman/dive" # Use DOCKER_HOST to work with rootless

alias dua='du -ahd1 | sort -rh'

# GIT ALIASES
alias grm='git ls-files --deleted -z | xargs -0 git rm'
alias gf='git fetch --all --prune'
alias gh="cd $(git rev-parse --show-toplevel)"
# git log, but just show current branch, master, and dev (if they exist, and their remotes)
alias gitlog='git log $($HOME/.dotfiles/scripts/get_remotes master dev HEAD) --graph --color --decorate --first-parent -m'
# git log, but just show current branch, master, and dev (if they exist, and their remotes)
alias gitlog-full='git log $($HOME/.dotfiles/scripts/get_remotes master dev HEAD)  --graph --color --decorate'
alias gitlogall='git log  --graph --branches --all --color --decorate --first-parent -m'
alias gitlogall-full='git log  --graph --branches --all --color --decorate'
alias gl="gitlog"
alias glf="gitlog-full"
alias gla="gitlogall"
alias glaf="gitlogall-full"
alias gcm='git commit -m'
alias gca='git commit --amend'
alias gcan='git commit --amend --no-edit'

alias pr='pdm run'
alias pri="pdm run ipython"

# KUBERNETES ALIASES
alias ktl='kubectl'
alias ktx='kubectx'
alias kns='kubens'

setopt nosharehistory                 # Prevent command history from being shared within windows
# These lines prevent command-matching when moving through command history
bindkey "\eOA" up-line-or-history    
bindkey "\eOB" down-line-or-history

bindkey "^[i" up-line-or-history
bindkey "^[k" down-line-or-history
bindkey "^[l" forward-char
bindkey "^[j" backward-char
bindkey "^[o" forward-word
bindkey "^[u" backward-word


# This fixes the issue where the return key doesn't work on some OS's
# Somehow return stops sending the ^M code, and sends this instead
# So we just set zsh to accept that as return
bindkey '^[OM' accept-line

# SOURCING
#======================================================
# source all files in .dotfiles/scripts
for f in $HOME/.dotfiles/scripts/*.sh; do
    source $f
done

# OS-Specific Config
#======================================================
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)        
        alias ls='ls -CFG --color'
        DIST=$(cat /etc/*-release)
        if echo $DIST | grep -q debian; then
            export LS_COLORS="$LS_COLORS:ow=1;34:tw=1;34:"
        fi
        ;;
    Darwin*) ;;
    CYGWIN*)
        alias ls='ls -CFG --color'
        ;;
    MINGW*)  ;;
esac

# WSL specific config
if uname -r | grep -q 'microsoft' ; then
    export DISPLAY="`grep nameserver /etc/resolv.conf | sed 's/nameserver //'`:0"
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH=$HOME/.npm-global/bin:$PATH

if [ $TERM = dumb ]; then
    unsetopt zle
    PS1='$ '
fi

# Homebrew autocomplete
autoload -Uz compinit
compinit
